parameters:
    blackknight467.service.smartystreets: blackknight467\SmartyStreetsBundle\Service\SmartyStreetsService

services:
    blackknight467.smarty_streets:
        class: %blackknight467.service.smartystreets%
        arguments: [%blackknight467_smartystreets.auth_id%, %blackknight467_smartystreets.auth_token%]
